import '@/styles/globals.scss';
import Script from 'next/script';
import { PropsWithChildren } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='ja'>
      <Script
        src={'https://kit.fontawesome.com/856e70b319.js'}
        crossOrigin='anonymous'
      />
      <body>{children}</body>
    </html>
  );
}
